### ISSUE TITLE
Facial Recognition Options

### ISSUE THREAD

**Issue by camcarlton** [CodeSpaceHQ/Telescreen#4]
Go through Rekgonition (AWS)

**Comment by dlowrey** [comment]
I like the idea of facial recognition and detection services and it would take the burden of computing power off our hands but I have a few concerns:

1.  Free tier / pricing / limits
2. When do we actually invoke the service? Would we detect on our system and once we detect a face then invoke the service?
3. How many times do we invoke the service when we detect a face? Once every N seconds? Surely we don't want to invoke it every time we detect a face... wouldn't that be slow? 

Just some of my concerns. But if we could figure those out then I am all for it, Microsoft or Amazon just might have a better chance at recognition than us...

**Comment by camcarlton** [comment]
From what I can tell they are both API Library that we can call within our scripts. So we decide when/how much we invoke the service. So we can create logic to know when to invoke either API. 

pricing information: https://docs.google.com/document/d/170A35oNU7ru1JmiB_yGsw0XqCPn3nG7g4YqKKnw3_zg/edit?usp=sharing

**Comment by NilsG-S** [comment]
More local options:

- https://github.com/cmusatyalab/openface
- http://openbiometrics.org/

**Comment by dlowrey** [comment]
@camcarlton the Microsoft Azure one looks promising. But I am worried about the logic as to when to use the API. We would still have to run detection on our machines, but when we detect a  face and it stays in the frame we will be calling the API at a rate of however many FPS we have the camera set at. Realistically if we only demo it for say, a few minutes, then we wouldn't really have to worry. But if our system was going to be on 24/7 it would be expensive!

**Comment by camcarlton** [comment]
@dlowrey Right. So do you want more infromation? I am currenttly trying both API to see what it can do, how it really works and can we control it to a inexpensive point

**Comment by dlowrey** [comment]
Actually I think I have an idea. What if we run the detection part on our systems, and we keep count of how many faces are in a frame. If the count remains the same OR reduces, we don't send it off to get the faces recognized. If the count increases then we send that frame off to recognize the faces. That way we are only using our resources (API calls, or expensive CPU time detecting faces) when there is most likely a new face in the frame. I think this would allow us to keep under the free tier for API calls, or if we run without API calls it will let us not waste time on recognizing the same face over and over.

**Comment by dlowrey** [comment]
@camcarlton No it's good, keep trying out the API's and see which one would better work for us!

**Comment by camcarlton** [comment]
Okay, it is so far not as easy to implement the AWS API as it is to get OpenCV running. I think the logic you described will be the best way to run our systems as of now, since we are not set on our face recognition flow yet.

**Comment by dlowrey** [comment]
Okay. And the virtual machine pre-packed with all of the OpenCV, and other facial recognition stuff we would use is very slow. I think I will try to get everything installed on a Raspberry Pi and start messing with it more there.
